services:

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "Root123!"
    ports:
      - "8081:80"
    volumes:
      - seq-data:/data
    networks:
      - taskboard-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskboard_db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "StrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - taskboard-net

  api:
    build:
      context: .
      dockerfile: Sources/TaskBoard.Api/Dockerfile
    container_name: taskboard-api
    restart: unless-stopped
    depends_on:
      - db
      - seq
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=TaskBoard;User ID=sa;Password=Admin123!;Encrypt=False;TrustServerCertificate=True;"
      Jwt__Key: "SuperSecretKeyForJwt123!"
      Jwt__Issuer: "TaskBoard"
      Jwt__Audience: "TaskBoardUsers"
      Serilog__WriteTo__1__Args__serverUrl: "http://seq"
    ports:
      - "8080:8080"
    networks:
      - taskboard-net

volumes:
  seq-data:
  sql-data:

networks:
  taskboard-net:
    driver: bridge
