version: "3.9"

services:

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "Root123!"
    ports:
      - "8081:80"
    volumes:
      - seq-data:/data
    networks:
      - taskboard-net

  db:
    image: postgres:16
    container_name: taskboard_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskboard
      POSTGRES_PASSWORD: StrongPassword123!
      POSTGRES_DB: TaskBoard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taskboard-net

  api:
    build:
      context: .
      dockerfile: Sources/TaskBoard.Api/Dockerfile
    container_name: taskboard-api
    restart: unless-stopped
    depends_on:
      - db
      - seq
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=TaskBoard;Username=taskboard;Password=StrongPassword123!"
      Jwt__Key: "SuperSecretKeyForJwt123!"
      Jwt__Issuer: "TaskBoard"
      Jwt__Audience: "TaskBoardUsers"
      Serilog__WriteTo__1__Args__serverUrl: "http://seq"
    ports:
      - "8080:8080"
    networks:
      - taskboard-net

volumes:
  seq-data:
  postgres-data:

networks:
  taskboard-net:
    driver: bridge
