name: CI-CD Backend

on:
  push:
    branches:
      - develop

jobs:

  build:
    name: Build, Test, Scan, Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Sources/TaskBoard.Api/TaskBoard.Api.csproj

      - name: Build
        run: dotnet build Sources/TaskBoard.Api/TaskBoard.Api.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/taskboard-api:latest \
            -f Sources/TaskBoard.Api/Dockerfile .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/taskboard-api:latest


  deploy-staging:
    name: Deploy to Render Staging
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": true}' \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
